version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GOLANG_VERSION: ${GOLANG_VERSION}
    ports:
      - 8080:8080
    volumes:
      - ./:/app
